name: flutter_application_4
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  fl_chart: ^0.55.2
  http: ^0.13.6
  path: ^1.8.2
  image_picker: ^0.8.7+5
  firebase_storage: ^11.6.0
  shared_preferences: ^2.0.15

  pdf: ^3.8.4
  printing: ^5.9.3

  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/icon.jpg
